import type { CodegenConfig } from '@graphql-codegen/cli';

/**
 * Schema is generated by Nest's `autoSchemaFile` at APP BOOT — not at `nest build`.
 * Quy trình bắt buộc: chạy API → `apps/api/schema.graphql` cập nhật → mới chạy codegen.
 * Chạy codegen trên SDL cũ cho ra types "xanh mà sai".
 */
const config: CodegenConfig = {
  schema: '../../apps/api/schema.graphql',
  generates: {
    'src/generated/index.ts': {
      plugins: ['typescript'],
    },
  },
  config: {
    // Package chỉ-có-type (`main` trỏ thẳng vào .ts): enum runtime sẽ kéo giá trị JS
    // vào bundle web không cần thiết, nên sinh union type thay vì `enum`.
    enumsAsTypes: true,
    useTypeImports: true,
    scalars: {
      DateTime: 'string',
    },
  },
};

export default config;
